### ISSUE TITLE
Readme.md needs to be README.md

### ISSUE THREAD

**Issue by simonbennie** [kaieberl/paper2speech#5]
Hi, just trying out your repo, but right now, there is a build error with pip when trying to build from scratch.

When I run as is I get:

`  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/bennie/paper2speach/paper2speech/setup.py", line 7, in <module>
          long_description=open('README.md').read(),
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.`

Renaming the Readme to all caps allows the reop to build though.

**Comment by kaieberl** [comment]
Thanks for pointing that out, it should be fixed now.
